name: Publish to pub.dev

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    name: "Publish to pub.dev"
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: dart --version
      - run: flutter --version

      - name: Publish to pub.dev
        run: dart pub publish -f
